/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 10 07:34:36 GMT 2020
 */

package com.brmayi.yuna;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.brmayi.yuna.Application;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Application_ESTest extends Application_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Application application0 = new Application();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "6DR0S:nz&,}2JhkVu1";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "";
      // Undeclared exception!
      try { 
        Application.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.boot.autoconfigure.condition.OnClassCondition", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Application application0 = new Application();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "?Y|j";
      stringArray0[1] = "n*v9OMlwK9f";
      stringArray0[2] = "";
      stringArray0[3] = "$`OK4";
      stringArray0[4] = "1\"vd|WA+278 /xai#t";
      stringArray0[5] = "uG)K+<-P~Ce$-#";
      stringArray0[6] = "I':FOJVw";
      stringArray0[7] = "";
      stringArray0[8] = "~x";
      // Undeclared exception!
      try { 
        Application.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.boot.autoconfigure.condition.OnClassCondition", e);
      }
  }
}
