/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 10 07:32:26 GMT 2020
 */

package com.brmayi.yuna.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.brmayi.yuna.util.DemoHystrixCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DemoHystrixCommand_ESTest extends DemoHystrixCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DemoHystrixCommand demoHystrixCommand0 = new DemoHystrixCommand();
  }
}
