server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://XXX?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: XXX
    password: XXX

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

dingtalk:
  accessToken: XX
  secret: XX
