/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 10 07:31:24 GMT 2020
 */

package com.brmayi.yuna.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.brmayi.yuna.service.ShowUndeclaredService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ShowUndeclaredService_ESTest extends ShowUndeclaredService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ShowUndeclaredService showUndeclaredService0 = new ShowUndeclaredService();
      // Undeclared exception!
      try { 
        showUndeclaredService0.showException();
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.brmayi.yuna.service.ShowUndeclaredService", e);
      }
  }
}
