/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 10 07:25:33 GMT 2020
 */

package com.brmayi.yuna.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.brmayi.yuna.model.Pojo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Pojo_ESTest extends Pojo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setId((-1));
      pojo0.hashCode();
      assertEquals((-1), pojo0.getId());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setId((-2145));
      Pojo pojo1 = new Pojo();
      boolean boolean0 = pojo0.equals(pojo1);
      assertEquals((-2145), pojo0.getId());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      boolean boolean0 = pojo0.equals(pojo0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setValue("B");
      String string0 = pojo0.getValue();
      assertEquals("B", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setValue("");
      String string0 = pojo0.getValue();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setId(1240);
      int int0 = pojo0.getId();
      assertEquals(1240, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setId((-1));
      int int0 = pojo0.getId();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      boolean boolean0 = pojo0.canEqual(pojo0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      boolean boolean0 = pojo0.canEqual("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      int int0 = pojo0.getId();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      String string0 = pojo0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setValue("");
      Pojo pojo1 = new Pojo();
      assertFalse(pojo1.equals((Object)pojo0));
      
      pojo1.setValue("");
      boolean boolean0 = pojo0.equals(pojo1);
      assertTrue(pojo1.equals((Object)pojo0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      Pojo pojo1 = new Pojo();
      assertTrue(pojo1.equals((Object)pojo0));
      
      pojo1.setValue("| X0p T=A} ");
      boolean boolean0 = pojo0.equals(pojo1);
      assertFalse(pojo1.equals((Object)pojo0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      Pojo pojo1 = new Pojo();
      pojo0.setId(3524);
      boolean boolean0 = pojo0.equals(pojo1);
      assertEquals(3524, pojo0.getId());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      boolean boolean0 = pojo0.equals("| X0p T=A} ");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setValue("Pojo(id=0, value=null)");
      Pojo pojo1 = new Pojo();
      boolean boolean0 = pojo0.equals(pojo1);
      assertEquals(0, pojo1.getId());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      pojo0.setValue("");
      pojo0.hashCode();
      assertEquals(0, pojo0.getId());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      Pojo pojo1 = new Pojo();
      boolean boolean0 = pojo0.equals(pojo1);
      assertEquals(0, pojo1.getId());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Pojo pojo0 = new Pojo();
      String string0 = pojo0.toString();
      assertEquals("Pojo(id=0, value=null)", string0);
  }
}
