/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 10 07:29:24 GMT 2020
 */

package com.brmayi.yuna.util;

import org.junit.Test;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import com.brmayi.yuna.util.ObjProxy;

import java.lang.reflect.Method;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class ObjProxy_ESTest extends ObjProxy_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        ObjProxy objProxy0 = new ObjProxy("=");
        try {
            objProxy0.invoke("=", (Method) null, (Object[]) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("com.brmayi.yuna.util.ObjProxy", e);
        }
    }
}